name: Check Minecraft Version
on:
   schedule:
    - cron:  '0/30 * * * *'
   workflow_dispatch:
      
jobs:
   check_mcv:
      runs-on: ubuntu-latest
      steps:
       - name: 签出储存库
         uses: actions/checkout@v4
       - name: 配置 Python 环境
         uses: actions/setup-python@v4
         with:
           python-version: 3.11
       - name: 安装依赖
         run: |
            python -m pip install --upgrade pip
            pip install requests
       - name: 运行更新脚本
         id: run_script
         run: python action.py
       - name: 提交与推送更改
         if: ${{ env.require_update }}
         run: |
            git add *
            git diff-index --quiet HEAD || git commit -S -m "preloaded new version" && git push
